-- ─────────────────────────────────────────────────────────────────────────────
-- Solvia Crystals — Orders Schema
-- Migration: 001_orders
--
-- HOW TO APPLY:
--   Option A (Supabase Dashboard):
--     1. Open your Supabase project → SQL Editor
--     2. Paste this entire file and click Run
--
--   Option B (Supabase CLI):
--     1. npx supabase login
--     2. npx supabase db push
--
-- NOTES:
--   • All monetary values stored as INTEGER paise (₹1 = 100 paise).
--     This eliminates floating-point precision bugs.
--     Display layer converts via: amount_paise / 100.
--   • `items` is a JSONB snapshot of OrderItem[] at time of purchase.
--     Product prices are locked here — never reconstructed from the live catalogue.
--   • RLS is enabled. No public policy = no browser access.
--     All reads/writes go through API routes using the service-role key.
-- ─────────────────────────────────────────────────────────────────────────────

-- ─── 1. Create orders table ──────────────────────────────────────────────────

create table if not exists public.orders (

  -- ── Identity ──────────────────────────────────────────────────────────────
  id                   text        primary key,
  -- e.g. "SOL-AB12CD" — generated by generateOrderId() in src/lib/orders.ts

  razorpay_order_id    text        not null unique,
  -- e.g. "order_PzlXXXXXXXXX" — set at create-order time

  razorpay_payment_id  text        unique,
  -- e.g. "pay_PzlXXXXXXXXX" — null until payment is verified

  -- ── Status ────────────────────────────────────────────────────────────────
  payment_status       text        not null default 'pending'
    constraint orders_payment_status_check
    check (payment_status in ('pending', 'paid', 'failed', 'refunded')),

  fulfillment_status   text        not null default 'processing'
    constraint orders_fulfillment_status_check
    check (fulfillment_status in ('processing', 'packed', 'shipped', 'delivered', 'cancelled')),

  -- ── Customer ──────────────────────────────────────────────────────────────
  customer_email       text        not null,
  customer_first_name  text        not null,
  customer_last_name   text        not null,
  customer_phone       text,

  -- ── Shipping Address ──────────────────────────────────────────────────────
  shipping_address     text        not null,
  shipping_city        text        not null,
  shipping_state       text        not null,
  shipping_zip         text        not null,
  shipping_country     text        not null,

  -- ── Items Snapshot ────────────────────────────────────────────────────────
  -- JSONB array of OrderItem objects — prices locked at checkout time.
  -- Schema: [{ productId, name, slug, price, quantity, image }]
  items                jsonb       not null default '[]'::jsonb,

  -- ── Financials (all in paise — integer) ───────────────────────────────────
  subtotal_paise       integer     not null check (subtotal_paise >= 0),
  shipping_paise       integer     not null check (shipping_paise >= 0),
  tax_paise            integer     not null check (tax_paise >= 0),
  discount_paise       integer     not null default 0 check (discount_paise >= 0),
  total_paise          integer     not null check (total_paise >= 0),

  -- ── Optional ──────────────────────────────────────────────────────────────
  coupon_code          text,
  notes                text,

  -- ── Audit ─────────────────────────────────────────────────────────────────
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now(),

  -- Null until the confirmation email was successfully accepted by the provider.
  -- Used to prevent duplicate confirmation emails from both verify + webhook.
  email_sent_at        timestamptz
);

-- ─── 2. Indexes ──────────────────────────────────────────────────────────────

-- Customer order history lookup
create index if not exists orders_customer_email_idx
  on public.orders (customer_email);

-- Webhook lookup by Razorpay order ID
create index if not exists orders_razorpay_order_id_idx
  on public.orders (razorpay_order_id);

-- Status filtering for admin panel (future)
create index if not exists orders_payment_status_idx
  on public.orders (payment_status);

create index if not exists orders_created_at_idx
  on public.orders (created_at desc);

-- ─── 3. Auto-update updated_at ───────────────────────────────────────────────

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists orders_set_updated_at on public.orders;

create trigger orders_set_updated_at
  before update on public.orders
  for each row
  execute function public.set_updated_at();

-- ─── 4. Row Level Security ───────────────────────────────────────────────────
-- Enable RLS. No policies = zero public access.
-- The service-role key (used in API routes) bypasses RLS entirely via
-- the Postgres BYPASSRLS privilege — no policy is needed for server access.

alter table public.orders enable row level security;

-- ─────────────────────────────────────────────────────────────────────────────
-- Migration complete.
-- Apply this migration before starting the application.
-- ─────────────────────────────────────────────────────────────────────────────
